#https://www.practicepython.org/exercise/2014/02/15/03-list-less-than-ten.html

import random

size = int(input("How big you want the list to be?: "))

lista1 = []
for i in range(0,size):
    n = random.randint(1,15)
    lista1.append(n)
print(f"This is the random autogenerated list: {lista1}")

list2 =[]

for l in lista1:
    if l <6:
        #print(l)
        list2.append(l)


print(f"This list only contains numbers equal or smaller than 5: {list2}")
    